from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import random

app = FastAPI(title="Quotes API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

quotes = [
    {"author": "Albert Einstein", "text": "A imaginação é mais importante que o conhecimento."},
    {"author": "Isaac Newton", "text": "Se vi mais longe, foi por estar sobre ombros de gigantes."},
    {"author": "Marie Curie", "text": "Nada na vida deve ser temido, apenas compreendido."},
    {"author": "Nikola Tesla", "text": "O futuro mostrará os resultados e julgará cada um conforme o seu trabalho."},
    {"author": "Sócrates", "text": "Conhece-te a ti mesmo."},
    {"author": "Aristóteles", "text": "Somos o que fazemos repetidamente. A excelência, portanto, não é um ato, mas um hábito."},
    {"author": "Platão", "text": "A maior riqueza é contentar-se com pouco."},
    {"author": "Leonardo da Vinci", "text": "A simplicidade é o último grau da sofisticação."},
    {"author": "Confúcio", "text": "Não importa o quão devagar você vá, desde que você não pare."},
    {"author": "Dalai Lama", "text": "A paz interior é a verdadeira chave para a felicidade."},
    {"author": "Mahatma Gandhi", "text": "Seja a mudança que você quer ver no mundo."},
    {"author": "Martin Luther King Jr.", "text": "A escuridão não pode expulsar a escuridão; só a luz pode fazer isso."},
    {"author": "Jesus Cristo (Mateus 5:9)", "text": "Bem-aventurados os pacificadores, porque serão chamados filhos de Deus."},
    {"author": "Provérbios 3:5-6", "text": "Confia no Senhor de todo o teu coração e não te apoies no teu próprio entendimento."},
    {"author": "Salmo 23:1", "text": "O Senhor é o meu pastor, nada me faltará."},
    {"author": "Paulo (1 Coríntios 13:13)", "text": "Agora, pois, permanecem a fé, a esperança e o amor, estes três, mas o maior destes é o amor."},
    {"author": "Fernando Pessoa", "text": "Tudo vale a pena quando a alma não é pequena."},
    {"author": "Clarice Lispector", "text": "Liberdade é pouco. O que eu desejo ainda não tem nome."},
    {"author": "C.S. Lewis", "text": "Você nunca é velho demais para definir uma nova meta ou sonhar um novo sonho."},
    {"author": "Victor Hugo", "text": "Nada é tão poderoso quanto uma ideia cujo tempo chegou."},
    {"author": "Nelson Mandela", "text": "A educação é a arma mais poderosa que você pode usar para mudar o mundo."},
    {"author": "Mário Quintana", "text": "O segredo é não correr atrás das borboletas... É cuidar do jardim para que elas venham até você."},
    {"author": "William Shakespeare", "text": "Somos feitos da mesma matéria que os sonhos."},
    {"author": "Buda", "text": "O que somos é consequência do que pensamos."},
    {"author": "Vincent van Gogh", "text": "O que seria da vida se não tivéssemos a coragem de tentar algo novo?"},
    {"author": "Rumi", "text": "Não se contente com histórias, com o que aconteceu com os outros. Desdobre o seu próprio mito."},
    {"author": "Sêneca", "text": "Nenhum vento é favorável para quem não sabe para onde vai."},
    {"author": "Agostinho de Hipona", "text": "Ama e faz o que quiseres."},
    {"author": "Hebreus 11:1", "text": "A fé é o firme fundamento das coisas que se esperam e a prova das coisas que não se veem."},
    {"author": "Francisco de Assis", "text": "Comece fazendo o que é necessário, depois o que é possível, e de repente você estará fazendo o impossível."},
    {"author": "Eleanor Roosevelt", "text": "O futuro pertence àqueles que acreditam na beleza de seus sonhos."},
    {"author": "Salmo 37:5", "text": "Entrega o teu caminho ao Senhor, confia nele, e ele tudo fará."},
    {"author": "Charles Chaplin", "text": "A vida é uma peça de teatro que não permite ensaios. Por isso, cante, ria, dance e viva intensamente."},
    {"author": "Lao Tsé", "text": "Um bom viajante não tem planos fixos e não está preocupado em chegar."},
    {"author": "Epicteto", "text": "Não é o que acontece com você, mas como você reage ao que acontece que importa."},
    {"author": "Albert Schweitzer", "text": "O exemplo não é a principal forma de influenciar os outros, é a única."},
    {"author": "Henry Ford", "text": "Se você pensa que pode ou que não pode, de qualquer forma você está certo."},
    {"author": "Steve Jobs", "text": "A inovação distingue um líder de um seguidor."},
    {"author": "Walt Disney", "text": "Se você pode sonhar, você pode fazer."},
    {"author": "Sun Tzu", "text": "A suprema arte da guerra é derrotar o inimigo sem lutar."},
    {"author": "Oscar Wilde", "text": "Viver é a coisa mais rara do mundo. A maioria das pessoas apenas existe."},
    {"author": "Machado de Assis", "text": "A vida é uma enorme loteria: os prêmios são poucos, e os azarados, muitos."},
    {"author": "Monteiro Lobato", "text": "Um país se faz com homens e livros."},
    {"author": "Rubem Alves", "text": "Ostra feliz não faz pérola."},
    {"author": "Guimarães Rosa", "text": "O correr da vida embrulha tudo. A vida é assim: esquenta e esfria, aperta e daí afrouxa."},
    {"author": "João 8:32", "text": "E conhecereis a verdade, e a verdade vos libertará."},
    {"author": "Romanos 12:21", "text": "Não te deixes vencer do mal, mas vence o mal com o bem."},
    {"author": "Provérbios 4:23", "text": "Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as fontes da vida."},
    {"author": "Isaías 41:10", "text": "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus."},
    {"author": "Salmo 91:1", "text": "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará."},
    {"author": "Tolkien", "text": "Nem todos os que vagueiam estão perdidos."},
    {"author": "Carl Jung", "text": "Quem olha para fora, sonha; quem olha para dentro, desperta."},
    {"author": "Sigmund Freud", "text": "Ser completamente honesto consigo mesmo é um bom exercício."},
    {"author": "Edgar Allan Poe", "text": "Aqueles que sonham de dia conhecem muitas coisas que escapam aos que sonham apenas à noite."},
    {"author": "George Orwell", "text": "Liberdade é o direito de dizer às pessoas o que elas não querem ouvir."},
    {"author": "Voltaire", "text": "Posso não concordar com o que você diz, mas defenderei até a morte o seu direito de dizê-lo."},
    {"author": "René Descartes", "text": "Penso, logo existo."},
    {"author": "Jean-Jacques Rousseau", "text": "O homem nasce livre, e por toda parte encontra-se acorrentado."},
    {"author": "Bíblia - Filipenses 4:13", "text": "Posso todas as coisas naquele que me fortalece."},
    {"author": "Eclesiastes 3:1", "text": "Tudo tem o seu tempo determinado, e há tempo para todo propósito debaixo do céu."},
    {"author": "Mateus 7:7", "text": "Pedi, e dar-se-vos-á; buscai, e achareis; batei, e abrir-se-vos-á."},
    {"author": "Provérbios 22:6", "text": "Instrui o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele."},
    {"author": "Provérbios 17:22", "text": "O coração alegre é bom remédio, mas o espírito abatido faz secar os ossos."},
    {"author": "Provérbios 16:9", "text": "O coração do homem traça o seu caminho, mas o Senhor lhe dirige os passos."},
    {"author": "Romanos 8:28", "text": "Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus."},
    {"author": "Salmo 46:1", "text": "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia."},
    {"author": "Benjamin Franklin", "text": "Investir em conhecimento sempre rende os melhores juros."},
    {"author": "Abraham Lincoln", "text": "Quase todos os homens são capazes de suportar a adversidade, mas se quiser por à prova o caráter de um homem, dê-lhe poder."},
    {"author": "George Bernard Shaw", "text": "A vida não é sobre encontrar a si mesmo, mas sobre criar a si mesmo."},
    {"author": "John Lennon", "text": "A vida é o que acontece enquanto você está ocupado fazendo outros planos."},
    {"author": "Bob Marley", "text": "Não viva para que a sua presença seja notada, mas para que a sua falta seja sentida."},
    {"author": "Chico Xavier", "text": "Embora ninguém possa voltar atrás e fazer um novo começo, qualquer um pode começar agora e fazer um novo fim."},
    {"author": "Pe. Fábio de Melo", "text": "A fé nos faz ver o invisível, crer no inacreditável e receber o impossível."},
    {"author": "Santa Teresa de Calcutá", "text": "Não podemos fazer grandes coisas, apenas pequenas coisas com grande amor."},
    {"author": "Salmo 121:1-2", "text": "Elevo os meus olhos para os montes; de onde me virá o socorro? O meu socorro vem do Senhor."},
    {"author": "Provérbios 15:1", "text": "A resposta branda desvia o furor, mas a palavra dura suscita a ira."},
    {"author": "Eclesiastes 7:8", "text": "Melhor é o fim das coisas do que o seu princípio."},
    {"author": "Mateus 6:34", "text": "Não vos inquieteis, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo."},
    {"author": "João 13:34", "text": "Um novo mandamento vos dou: que vos ameis uns aos outros, assim como eu vos amei."},
    {"author": "Isaías 40:31", "text": "Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias."},
    {"author": "Salmo 118:24", "text": "Este é o dia que fez o Senhor; regozijemo-nos e alegremo-nos nele."},
    {"author": "Provérbios 19:21", "text": "Muitos propósitos há no coração do homem, mas o conselho do Senhor permanecerá."},
    {"author": "Mateus 11:28", "text": "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei."},
    {"author": "João 14:27", "text": "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá."},
    {"author": "Salmo 9:10", "text": "Em ti confiarão os que conhecem o teu nome, porque tu, Senhor, não desamparas os que te buscam."},
    {"author": "Romanos 15:13", "text": "Que o Deus da esperança vos encha de todo gozo e paz em crença, para que abundeis em esperança pelo poder do Espírito Santo."},
    {"author": "Salmo 27:1", "text": "O Senhor é a minha luz e a minha salvação; a quem temerei?"},
    {"author": "Isaías 26:3", "text": "Tu conservarás em paz aquele cuja mente está firme em ti, porque ele confia em ti."},
    {"author": "Provérbios 11:25", "text": "A alma generosa prosperará, e quem dá a beber será dessedentado."},
    {"author": "Romanos 5:3-4", "text": "A tribulação produz paciência, a paciência experiência, e a experiência esperança."},
    {"author": "Tiago 1:5", "text": "Se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente."},
    {"author": "Mateus 19:26", "text": "Para os homens é impossível, mas para Deus tudo é possível."}
]

@app.get("/")
def get_quote():
    return random.choice(quotes)

@app.get("/api")
def root():
    return {"message": "Quotes API running 🚀"}